---
- name:  Deploying server configuration to all provisioned servers
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root

  vars:
    - ansible_host_key_checking: False


  roles:
    - apache
